### ISSUE TITLE
Performing select query after update results in an error 

### ISSUE THREAD

**Issue by dkrantsberg** [thomasfr/node-sparql-client#11]
If you do select query following an update/delete query it results in both *query* and *update* parameters being passed to the sparql endpoint. This results in an error. 
The error response from AllegroGraph server is: "INVALID PARAMETERS: Must specify query or update but not both."

**Comment by thomasfr** [comment]
This is fixed right? Can you close this issue if fixed?

**Comment by dkrantsberg** [comment]
Closing.
