### ISSUE TITLE
response.statusCode == 503 results in crash

### ISSUE THREAD

**Issue by pheyvaer** [thomasfr/node-sparql-client#6]
When response.statusCode == 503 (when executing a query), error == null.
So the code error.code leads to a crash (client.js:43).

EDIT: acutally any response.statusCode >= 300 where error == null

**Comment by thomasfr** [comment]
This is fixed? If so, please close this issue. Thank you again!

**Comment by pheyvaer** [comment]
fixed with ebc228b026ec21088b990b313e8bb2b682728b77
